### ISSUE TITLE
com.google.code.gson.ane [META-INF/ANE/extension.xml]: error 102: Invalid namespace http://ns.adobe.com/air/extension/50.2

### ISSUE THREAD

**Issue by vetaldnepr** [distriqt/ANE-AndroidSupport#31]
I added a new com.google.code.gson.ane, and now I get an error when building apk.

##### Expected behaviour
Build apk successful

##### Actual behaviour
Build apk crashed

##### Environment 

- AIR SDK version: 50.2.2.5
- Device OS: -
- Device version: -
- Development IDE: FlashDevelop
- Development OS: Windows10

##### Logs
`E:\work\*\ane\com.google.code.gson.ane [META-INF/ANE/extension.xml]: error 102: Invalid namespace http://ns.adobe.com/air/extension/50.2`

**Comment by marchbold** [comment]
Please update to AIR 50.2, this is required to support the latest features in the com.google.code.gson extension.

**Comment by vetaldnepr** [comment]
I am using AIR SDK version 50.2.2.5.

**Comment by marchbold** [comment]
And have you set the namespace in your app descriptor to 50.2?

**Comment by vetaldnepr** [comment]
After, i change namespace in descriptor to `<application xmlns="http://ns.adobe.com/air/application/50.2">`, i get a new error `error 102: Invalid namespace http://ns.adobe.com/air/application/50.2`.

**Comment by marchbold** [comment]
Are you certain you are using AIR 50.2 to package your app?

**Comment by marchbold** [comment]
Yes you can enable debug logging in your `adt.cfg` or through the air sdk manager, and then look at the `adt.log` file in your home directory.

**Comment by marchbold** [comment]
@vetaldnepr That indicates you are using the legacy build method. Make sure you have android studio or the android sdk installed and have set the path in your air config. 

There are a lot of discussions on resolving this issue on the air forum: https://github.com/airsdk/Adobe-Runtime-Support/discussions/1782

**Comment by vetaldnepr** [comment]
Hi. I read it, but I don't quite understand what to do: 
- I deleted this line from my manifest.
`<BuildLegacyAPK>true</BuildLegacyAPK>`
- ANDROID_SDK path registered in **adt.cfg**.

but i still get an error on build.
Please, help me.

**adt.log**
`
*** ADT Logging at 2023/05/29 13:28:08 ***
Called by: E:\work\sdks\AIRSDK_Windows_50.2.2.5\lib\adt.jar
ADT 50.2.2.5 called with: -package -target apk-captive-runtime -arch armv7 -storetype jks -alias *** -keystore ***.jks -storepass xxxxxx ***.apk ***\out\Mobile-app.xml -resdir ***\android_res -extdir ***\ane -C ***\out ***.swf -C *** icons
Not requested a legacy APK build, but could not find Javac and/or Android SDK hence falling back to legacy build
Creating device SDK handler - location passed in = c:\Users\work-04\AppData\Local\Android\Sdk
Warning: Using default implementation for native extension 'com.adobe.ane.productStore'
AAPT command line: C:\Users\work-04\AppData\Local\Android\Sdk\build-tools\33.0.2\aapt.exe package -z -u -J C:\Users\work-04\AppData\Local\Temp\8bd9f1e8-15ac-4c0f-b1d9-9c50cc898395 -M C:\Users\work-04\AppData\Local\Temp\8bd9f1e8-15ac-4c0f-b1d9-9c50cc898395\AndroidManifest.xml -S ***\android_res -S C:\Users\work-04\AppData\Local\Temp\8bd9f1e8-15ac-4c0f-b1d9-9c50cc898395\app_entry_res -S C:\Users\work-04\AppData\Local\Temp\8bd9f1e8-15ac-4c0f-b1d9-9c50cc898395\captive_runtime_res -m --extra-packages com.distriqt.extension.bolts:com.distriqt.extension.firebase.crashlytics:com.gctech.extension:androidx.appcompat:androidx.appcompat.resources:com.vk.sdk:ru.ok.android.sdk:androidx.browser:com.distriqt.extension.googleidentity:com.google.android.gms.gcm:androidx.constraintlayout.widget:com.distriqt.extension.facebook.login:com.facebook.login:com.bumptech.glide:androidx.cardview:com.distriqt.extension.pushnotifications:com.google.firebase.messaging:com.google.firebase.inappmessaging.display:com.distriqt.extension.facebook.core:com.facebook.common:com.google.android.gms.auth:com.distriqt.extension.facebook.share:com.facebook.share:com.distriqt.extension.applesignin:com.distriqt.extension.facebook.gamingservices:androidx.activity:androidx.coordinatorlayout:androidx.core:androidx.drawerlayout:androidx.fragment:androidx.lifecycle.runtime:androidx.lifecycle.viewmodel:androidx.media:androidx.savedstate:androidx.startup:androidx.viewpager2:com.distriqt.extension.networkinfo:com.google.android.gms.base:com.google.android.gms.common: -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-bolts-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-firebase-crashlytics-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\com-gctech-extension-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\appcompat-1.6.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\appcompat-resources-1.6.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\com.marpies.ane.vk-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\Odnoklassniki-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\browser-1.5.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-googleidentity-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\play-services-gcm-17.0.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\constraintlayout-2.1.4-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-facebook-login-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\facebook-login-9.1.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\glide-4.12.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\cardview-1.0.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-pushnotifications-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\firebase-inappmessaging-display-20.1.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\firebase-messaging-23.0.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-facebook-core-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\facebook-common-9.1.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\play-services-auth-20.1.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-facebook-share-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\facebook-share-9.1.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-applesignin-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-facebook-gamingservices-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\activity-1.7.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\coordinatorlayout-1.2.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\core-1.9.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\drawerlayout-1.2.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\fragment-1.5.6-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\lifecycle-runtime-2.6.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\lifecycle-viewmodel-2.6.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\media-1.6.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\savedstate-1.2.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\startup-runtime-1.1.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\viewpager2-1.0.0-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\distriqt-extension-networkinfo-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\play-services-base-18.0.1-res -S C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\play-services-basement-18.0.0-res --auto-add-overlay -I E:\work\sdks\AIRSDK_Windows_50.2.2.5\lib\android\lib\resources\android-res.jar --no-version-vectors --min-sdk-version 14 --target-sdk-version 31 --version-code 1009004 --version-name 1.9.4 -F C:\Users\work-04\AppData\Local\Temp\8bd9f1e8-15ac-4c0f-b1d9-9c50cc898395\resources.apk
..java.lang.Thread.getStackTrace(Thread.java:1559)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init>(ADTException.java)
..com.adobe.air.apk.APKOutputStream.a(APKOutputStream.java)
..com.adobe.air.apk.APKOutputStream.addApplicationDescriptor(APKOutputStream.java)
..com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
ADT exception: aapt tool failed:C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\savedstate-1.2.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\lifecycle-viewmodel-2.6.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\lifecycle-runtime-2.6.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\activity-1.7.0-res\values\values.xml:4: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\constraintlayout-2.1.4-res\values\values.xml:1491: error: Attribute "android:translationX" has already been defined
C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\constraintlayout-2.1.4-res\values\values.xml:1495: error: Attribute "android:translationY" has already been defined
C:\Users\work-04\AppData\Local\Temp\eedd3c63-1cb8-42db-bdde-c55b3045f7c4\constraintlayout-2.1.4-res\values\values.xml:1498: error: Attribute "android:translationZ" has already been defined


`

**Comment by marchbold** [comment]
Have you installed the Android SDK? The error seems to indicate you haven't installed that? 

https://airsdk.dev/docs/basics/install/windows#install-android-studio

**Comment by vetaldnepr** [comment]
Of course i have Android SDK installed. I reinstalled sdk but nothing changed.

![изображение](https://github.com/distriqt/ANE-AndroidSupport/assets/5724002/06ba591b-9505-4a7a-a5c6-842df0b6aac6)

![изображение](https://github.com/distriqt/ANE-AndroidSupport/assets/5724002/ca958ebb-62bc-4795-ac17-5f6091c410c3)

**Comment by marchbold** [comment]
The error at the top seems to indicate it can't find it:

```
Not requested a legacy APK build, but could not find Javac and/or Android SDK hence falling back to legacy build
```

Maybe check the settings you have in your adt.cfg (either manually or through the air sdk manager)?

**Comment by vetaldnepr** [comment]
I think that the path to the SDK is correct, because if i set specify the wrong path in my adt.cfg, i get a different error text, like this:
`platformsdk must refer to a valid directory path - c:\Users\work-04\AppData\Local\Android_temp\Sdk`

**Comment by marchbold** [comment]
Very odd, that error message definitely indicates some issues. Could you try installing v33 of the build tools, perhaps something is amiss with your current version.

**Comment by vetaldnepr** [comment]
I installed 33.0.0 but still the same error:

`*** ADT Logging at 2023/06/06 20:15:44 ***
Called by: E:\work\sdks\AIRSDK_Windows_50.2.2.5\lib\adt.jar
ADT 50.2.2.5 called with: -package -target apk-captive-runtime -arch armv7 -storetype jks -alias webcam -keystore E:\work\***.jks -storepass xxxxxx E:\work\***.apk E:\work\***\out\Mobile-app.xml -resdir E:\work\***\android_res -extdir E:\work\***\ane -C E:\work\***.swf -C E:\work\*** icons
Not requested a legacy APK build, but could not find Javac and/or Android SDK hence falling back to legacy build
Creating device SDK handler - location passed in = C:\Users\work-04\AppData\Local\Android\Sdk
Warning: Using default implementation for native extension 'com.adobe.ane.productStore'
AAPT command line: C:\Users\work-04\AppData\Local\Android\Sdk\build-tools\33.0.0\aapt.exe package -z -u -J C:\Users\work-04\AppData\Local\Temp\462a1edb-cfcb-4544-ac06-cc79b81be993 -M C:\Users\work-04\AppData\Local\Temp\462a1edb-cfcb-4544-ac06-cc79b81be993\AndroidManifest.xml -S E:\work\***\android_res -S C:\Users\work-04\AppData\Local\Temp\462a1edb-cfcb-4544-ac06-cc79b81be993\app_entry_res -S C:\Users\work-04\AppData\Local\Temp\462a1edb-cfcb-4544-ac06-cc79b81be993\captive_runtime_res -m --extra-packages com.distriqt.extension.bolts:com.distriqt.extension.firebase.crashlytics:com.gctech.extension:androidx.appcompat:androidx.appcompat.resources:com.vk.sdk:ru.ok.android.sdk:androidx.browser:com.distriqt.extension.googleidentity:com.google.android.gms.gcm:androidx.constraintlayout.widget:com.distriqt.extension.facebook.login:com.facebook.login:com.bumptech.glide:androidx.cardview:com.distriqt.extension.pushnotifications:com.google.firebase.messaging:com.google.firebase.inappmessaging.display:com.distriqt.extension.facebook.core:com.facebook.common:com.google.android.gms.auth:com.distriqt.extension.facebook.share:com.facebook.share:com.distriqt.extension.applesignin:com.distriqt.extension.facebook.gamingservices:androidx.activity:androidx.coordinatorlayout:androidx.core:androidx.drawerlayout:androidx.fragment:androidx.lifecycle.runtime:androidx.lifecycle.viewmodel:androidx.media:androidx.savedstate:androidx.startup:androidx.viewpager2:com.distriqt.extension.networkinfo:com.google.android.gms.base:com.google.android.gms.common: -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-bolts-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-firebase-crashlytics-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\com-gctech-extension-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\appcompat-1.6.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\appcompat-resources-1.6.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\com.marpies.ane.vk-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\Odnoklassniki-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\browser-1.5.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-googleidentity-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\play-services-gcm-17.0.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\constraintlayout-2.1.4-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-facebook-login-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\facebook-login-9.1.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\glide-4.12.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\cardview-1.0.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-pushnotifications-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\firebase-inappmessaging-display-20.1.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\firebase-messaging-23.0.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-facebook-core-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\facebook-common-9.1.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\play-services-auth-20.1.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-facebook-share-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\facebook-share-9.1.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-applesignin-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-facebook-gamingservices-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\activity-1.7.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\coordinatorlayout-1.2.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\core-1.9.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\drawerlayout-1.2.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\fragment-1.5.6-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\lifecycle-runtime-2.6.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\lifecycle-viewmodel-2.6.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\media-1.6.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\savedstate-1.2.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\startup-runtime-1.1.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\viewpager2-1.0.0-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\distriqt-extension-networkinfo-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\play-services-base-18.0.1-res -S C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\play-services-basement-18.0.0-res --auto-add-overlay -I E:\work\sdks\AIRSDK_Windows_50.2.2.5\lib\android\lib\resources\android-res.jar --no-version-vectors --min-sdk-version 14 --target-sdk-version 31 --version-code 1009004 --version-name 1.9.4 -F C:\Users\work-04\AppData\Local\Temp\462a1edb-cfcb-4544-ac06-cc79b81be993\resources.apk
..java.lang.Thread.getStackTrace(Thread.java:1559)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init>(ADTException.java)
..com.adobe.air.apk.APKOutputStream.a(APKOutputStream.java)
..com.adobe.air.apk.APKOutputStream.addApplicationDescriptor(APKOutputStream.java)
..com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
ADT exception: aapt tool failed:C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\savedstate-1.2.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\lifecycle-viewmodel-2.6.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\lifecycle-runtime-2.6.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\activity-1.7.0-res\values\values.xml:4: error: Found tag id where item is expected

C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\constraintlayout-2.1.4-res\values\values.xml:1491: error: Attribute "android:translationX" has already been defined
C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\constraintlayout-2.1.4-res\values\values.xml:1495: error: Attribute "android:translationY" has already been defined
C:\Users\work-04\AppData\Local\Temp\1aaa96b4-3ce0-4634-9ec4-5f97b6f4675a\constraintlayout-2.1.4-res\values\values.xml:1498: error: Attribute "android:translationZ" has already been defined`

**Comment by marchbold** [comment]
Maybe it's the java version then, are you using v11 of the JDK?

**Comment by marchbold** [comment]
What extensions are you using, looks as though you have a conflict between kotlin versions. Are you using any that aren't from us?

**Comment by vetaldnepr** [comment]
Yes, there are other extensions. But there are also your extensions that have expired subscriptions. I will try disabling other extensions to try and fix the cause.

Tell me, this error cannot be due to the version of gradle? What version of gradle do you need to build?

**Comment by marchbold** [comment]
If you have installed android studio and are using the newer build method then the correct version of gradle should be downloaded as part of the build process and is specified by AIR.

**Comment by vetaldnepr** [comment]
hi. can i know where gradle will be downloaded? I'm using custom build gradle plugin, and I suspect that the reason is that I separately installed the wrong version of gradle.

**Comment by marchbold** [comment]
Maybe check this discussion to set the version in your app descriptor https://github.com/airsdk/Adobe-Runtime-Support/discussions/2701

**Comment by vetaldnepr** [comment]
I removed the old ANE from the project and the project was built. But an error occurs when the application starts:
**java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication"**


Logs from Logcat:

`
Process: air.com.myapp, PID: 14403
java.lang.RuntimeException: Unable to instantiate application android.support.multidex.MultiDexApplication: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/air.com.myapp-TCPCsB8y6gvSJCG6TJiJ3g==/base.apk"],nativeLibraryDirectories=[/data/app/air.com.myapp-TCPCsB8y6gvSJCG6TJiJ3g==/lib/arm, /data/app/air.com.myapp-TCPCsB8y6gvSJCG6TJiJ3g==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1060)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication" on path: DexPathList[[zip file "/data/app/air.com.myapp-TCPCsB8y6gvSJCG6TJiJ3g==/base.apk"],nativeLibraryDirectories=[/data/app/air.com.myapp-TCPCsB8y6gvSJCG6TJiJ3g==/lib/arm, /data/app/air.com.myapp-TCPCsB8y6gvSJCG6TJiJ3g==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1052)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877) 
	at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:193) 
	at android.app.ActivityThread.main(ActivityThread.java:6762) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
`

**Comment by marchbold** [comment]
@vetaldnepr Please remove all references to `android.support.multidex.MultiDexApplication`. That class hasn't been supported in a long time.

**Comment by vetaldnepr** [comment]
Thank you. That helped! Thank you very much for your help!
