### ISSUE TITLE
Issues updating to androidx.core missing resource and fileLoadException

### ISSUE THREAD

**Issue by Ender22** [distriqt/ANE-AndroidSupport#5]
Trying to update all of my ANE's to the current version but running into an issue.

What I've done:
- got most recent air 32 
- download newest versions of all ANE's I use
- went through manifest file and ensure all are up to date with what is written in the "Add the Extension" doc for each extension
- added libclang_rt.ios.a to lib/aot/lib because was getting an error without it
- followed the https://github.com/distriqt/ANE-AndroidSupport/blob/master/lib/README.md#migration and replaced old support extensions with androidx 

Now when I try to run the app:

ios - no issues

android - I get an error during compiling: "appcompat-1.0.0-res\values-v28\values-v28.xml:7: error: Error: No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius')."

windows 10 - I get an error shortly after app launch and app auto-closes:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'CoreLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG)) ---> System.ArgumentException: Absolute path information is required.
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Reflection.Assembly.LoadFile(String path)
   at DllResolution.GetAssembly(String baseDir, String dllName)
   at DllResolution.ResolveHandler(Object Sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at corens.InitController(Void* context)
   at core_contextInitializer(Void* extData, Byte* ctxType, Void* ctx, UInt32* numFunctionsToSet, FRENamedFunction_** functionsToSet)

any ideas what I've done wrong or how to troubleshoot?

**Comment by marchbold** [comment]
You need to use AIR 33 to support androidx. 

The build tools in AIR 32 are too old.

Also please be aware we are still releasing androidx compatible updates so some of the ANEs haven't been released yet. Please be patient but we are hoping to complete all the updates by the middle of the week. You can follow the release here: https://github.com/orgs/distriqt/projects/2

**Comment by marchbold** [comment]
If you need to stay on AIR 32, you should stay with the android support implementations. We have tagged all the repositories with a release/androidsupport tag that should be used.

**Comment by Ender22** [comment]
Okay, thanks
